export const EndpointConstants = {
    MsAllCategories: "cares/all",
    MsAllCategoriesWithProviders: "cares/getCaresWithProviders",
    MsProvidersDetailV2: "provider/findNearest",
    MsProviderInfo: "MsProviderInfo",
    MsProviderWithQA: "provider/qna/",
    SendEmail: "provider/email",
    SaveReport: "provider/report",
    Login: "login",
    Register: "user/create",
    Update: "user/update",
    UpdateProfile: "user/profile",
    Verify: "user/verify",
    RetryVerification: 'user/retryVerification',
    GetUserByEmail: 'user/getUserByEmail',
    CreateContactMessage: 'createContact',
    ForgotPassword: 'user/forgotPassword',
    ResetPassword: 'user/resetPassword',
    RemoveProfilePicture: 'user/removePicture',
    AddWishlist: 'wishlist',
    DeleteWishlist: 'deleteFromWishlist',
    GetWishlist: 'getWishlist',
    GetProvider: 'provider',
    ChangePassword: 'user/changePassword',
    SearchByProviderName:'provider/search',
    AdminLogin: "admin/login",
    VerifyProviders: "admin/verifyproviders",
    UpdateAgrReview:"admin/updateReview",
    GetDashboardProviderDetails:"admin/getProviderDetails",
    ClaimProvider: "provider/claim",
     GetAllContact:"admin/getAllContacts",
    ResolveTickets:"admin/resolveTicket",
    GetBusinessList: 'listOfBusiness/getBusinessList',
    UpsertProvider:'listOfBusiness/upsertProvider',
    DeleteProviderImage:'listOfBusiness/deleteImage',
    UpdateProviderService:'listOfBusiness/updateService',
    UpsertProviderLocation:'listOfBusiness/upsertLocation',
    GenerateOtp:'listOfBusiness/generateOtp',
    SaveContact:'listOfBusiness/saveContact',
    UpsertContactDetails:'listOfBusiness/upsertContactDetails',
    UpsertProviderImage:'listOfBusiness/upserProviderImage',
    ProviderProfile: "provider/profile",
    UploadLogo: "provider/update/logo",
    UpdateBasicInfo: "provider/update/basic-info",
    VerifyProviderEmail: "provider/verifyProviderEmail",
    VerifyProviderEmailOtp: "provider/email/verify",
    RemoveLogo: "provider/logo/remove",
    GetAllReports:"admin/getAllReports",
    ResolveReports:"admin/resolveReport",
    UpdateSocialMediaLink: "provider/socialMedia/update",
    DeleteSocialMediaLink: "provider/socialMedia/delete",   
    GetReportOptions: "report/getReportOptions",
    UpsertPrimaryPhoneNumber: "listOfBusiness/upsertPrimaryPhoneNumber",
    RemovePhoneNumber: "listOfBusiness/removePhoneNumber",
    UpsertContactDetailsWithoutOtp: "listOfBusiness/upsertContactDetailsWithoutOTP",
    RemoveAddress:"listOfBusiness/removeAddress",
    RemoveService:"listOfBusiness/removeService",
    GetAllProviderClaims:"admin/getAllProviderClaims",
    RemoveProvider:"listOfBusiness/removeProvider",
    GetSiteSettings:"admin/getSiteSettings",
    AddSettings:"admin/addSettings",
    UpdateSettings:"admin/updateSettings",
    UpdateSettingsAccess:"admin/updateAccess",
}